config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help' # 未実装
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :liked_posts
      post :gravatar_link
    end
  end
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[show new create destroy]
  resources :comments, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :like_post_relationships, only: %i[create destroy]

  post '/guestlogin', to: 'sessions#guest_login'
end

app/views/layouts/_footer.html.erb
<div class="font-small copyright">
    Copyright © 2021 Snomen All Rights Reserved.
</div>

app/views/layouts/_header.html.erb
<header class="fixed-top header-nav bg-light border-bottom">
    <nav class="h-100 d-flex align-items-center">
        <div class="my-2 mr-auto">
            <%= link_to image_tag('logo.png', size: '194x50', alt: "logo"), root_path %>
        </div>
        <%# <div class="my-2 mr-4 d-none d-md-block">
            <form class="form-inline">
                <input class="form-control mr-2" type="search" placeholder="検索" aria-label="Search">
                <button class="btn btn-dark my-0" type="submit">検索</button>
            </form>
        </div> %>
        <div class="mr-2 dropdown">
            <% if logged_in? %>
            <div class="dropdown-toggle" data-toggle="dropdown" id="user-menu">
                <%= icon_image current_user, add_class: "icon-medium" %>
            </div>
            <div class="dropdown-menu">
                <%= link_to "プロフィール", current_user, class: "dropdown-item" %>
                <%= link_to "アカウント設定", edit_user_path(current_user), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
            <% else %>
            <%= link_to "ログイン", login_path %>
            <% end %>
        </div>
    </nav>
</header>

app/views/layouts/_nav.html.erb
<%
    menuitems = [
        {icon: "home", text: "ホーム", link: root_path},
        # {icon: "notifications_none", text: "通知", link: ''},
        {icon: "favorite", text: "いいねした投稿", link: logged_in? ? liked_posts_user_path(current_user) : login_path },
        {icon: "edit", text: "投稿", aclass:"menu-post order-md-4", liclass: "justify-content-md-center", link: logged_in? ? new_post_path : login_path },
        {icon: "perm_identity", text: "フォローリスト", link: logged_in? ? following_user_path(current_user)  : login_path},
        {icon: "search", text: "ユーザーを探す", link: users_path},
        # {icon: "bookmark_border", text: "ブックマーク", link: ''},
        # {icon: "message", text: "メッセージ", link: ''},
    ]
        %>
<nav>
    <ul class="nav m-0 p-0 d-flex flex-md-column">

        <% menuitems.each do |item| %>
        <%= link_to item[:link], class: "menu-item px-0 border-bottom border-right p-md-3 text-dark nav-link #{item[:aclass]}" do %>
        <li
            class="h-100 d-flex flex-column flex-md-row justify-content-center align-items-center justify-content-md-start <%= item[:liclass] %>">
            <i class="material-icons font-ml mr-md-3"><%= item[:icon] %></i>
            <span class="font-small font-md-ms"><%= item[:text] %></span>
        </li>
        <% end %>
        <% end %>

    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body class="d-flex flex-column mb-md-0">
    <%= render 'layouts/header'%>
    <aside class="bg-lightdark d-md-flex flex-md-column">
        <%= render 'layouts/nav'%>
        <div class="d-none d-md-block mt-auto">
            <%= render 'layouts/footer'%>
        </div>
    </aside>
    <main class="p-2 flex-1">
        <div class="">
            <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
        </div>
    </main>
    <div class="p-3">
        <%= debug(params) if Rails.env.development? %>
    </div>
    <footer class="p-3 d-md-none mt-auto">
        <%= render 'layouts/footer'%>
    </footer>

</body>

</html>